blah:
	npx tsc -b
	cp js/html.js js/html.js.map ../http
	cp js/log.js js/log.js.map ../http
	cp js/storage.js js/storage.js.map ../http
	cp js/tabbed.js js/tabbed.js.map ../http

	cp js/js_simulation.js js/js_simulation.js.map ../http
	cp js/js_parameters.js js/js_parameters.js.map ../http
	cp js/simulation_controls.js js/simulation_controls.js.map ../http
	cp js/saved_simulations.js js/saved_simulations.js.map ../http
	cp js/visualize.js js/visualize.js.map ../http
	cp js/dk.js js/dk.js.map ../http
